### ISSUE TITLE
Detect error type and prevent end event to be triggered

### ISSUE THREAD

**Issue by karmac2015** [overlookmotel/got-resume#14]
How can I detect error type example (gotResume.CancelError)? and how can I prevent stream to trigger end event when error happens, I need to do process on end and if there is an error I want to skip this process

**Comment by overlookmotel** [comment]
Detect the type of the error in usual way `err instanceof gotResume.CancelError`.

An `end` event is always emitted after `error` event. No way to prevent it being emitted. This is the behavior of [got](https://www.npmjs.com/package/got). If you want to not act on the `end` event, you'd need to implement this yourself. Something like:

```js
let errored = false;

stream.on('error', err => {
  errored = true;
  // Handle error here
} );

stream.on('end', () => {
  if (errored) return;
  // Handle end here
} );
```

The code `// Handle end here` will only run if an `end` event is emitted with no `error` event first.

**Comment by karmac2015** [comment]
It is good option but I think if you implement that in your library, it will be a good enhancement,  because handling multiple request in this way need some management

**Comment by overlookmotel** [comment]
I'm afraid this behavior just mirrors [got](https://www.npmjs.com/package/got)'s behavior. If you feel it's incorrect or want a option to make the behavior customisable, I'd suggest raising an issue on got itself.

For what it's worth, I agree with you than if an `error` event is emitted, an `end` event should not be, but that's not how got works at present.

**Comment by karmac2015** [comment]
Thank you, I will add an issue on got
