### ISSUE TITLE
Cannot resume download

### ISSUE THREAD

**Issue by Nelife** [overlookmotel/got-resume#9]
He!
I have a problem!
it cannot resume download.
Thank you so much
```
app.get('/test', function (req, res) {
    let bytes = 0
    const url = 'https://c2-sd-vdc.nixcdn.com/PreNCT12/HoaTimNguoiXuaKaraoke-QuangLe-4601841.mp4?st=rclWIYzqLN_lij8UpM9Z0Q&e=1517999354&t=1517912951366';
    const stream = gotResume(url, {attempts: 0});
    stream.pipe(res);

});
```
![ws1q3](https://user-images.githubusercontent.com/12018657/35863104-3475243a-0b80-11e8-95dd-38c0abb0d590.jpg)
![tgxxm](https://user-images.githubusercontent.com/12018657/35863106-34d812e8-0b80-11e8-8b5f-53f31fa5024c.jpg)

**Comment by overlookmotel** [comment]
Hi @Nelife.

I think you're misunderstanding how you'd need to wire up the module so the output from your route handler is resumable.

At present, when your route is hit, there's info in the `req` headers that your download manager software is sending saying "give me the file starting at byte xxxx". But you're not doing anything with that info in the `req` object.

To make it work how you want, you'd need to extract the headers from `req`, feed that into got-resume via the `offset` and `length` options, and then also set the response headers in `res` accordingly.

That will all be quite complex to do. If you don't get what I'm talking about, you're probably better off using a dedicated proxy or something.

Sorry if this isn't as helpful as you'd like.

I'm closing this issue as it doesn't reveal a bug in got-resume.
